### ISSUE TITLE
template: member/single.html:92:29: executing "member/single.html" at <.id>: can't evaluate field id in type string

### ISSUE THREAD

**Issue by ShixiangWang** [biaslab/hugo-academic-group#39]
Hello,

the problem put as the title, how to fix this?

**Comment by CorradoLanera** [comment]
I have the same problem, at the very first run

**Comment by kanishkamisra** [comment]
Same problem here!

**Comment by ivan-bocharov** [comment]
Hi all,

Thanks for your feedback. The content of `exampleSite` folder was not updated to the latest changes in the theme. I have fixed the example website to address this issue.
